service: lfstats-chomper

frameworkVersion: "2"

useDotenv: true

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource:
            - "arn:aws:secretsmanager:us-east-1:474496752274:secret:prod/lfstats-MSO2km"
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::lfstats-incoming"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:DeleteObject"
          Resource:
            - "arn:aws:s3:::lfstats-incoming/*"
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::lfstats-scorecard-archive"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
          Resource:
            - "arn:aws:s3:::lfstats-scorecard-archive/*"
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 120
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true

functions:
  newChomper:
    handler: chomper.chomper
    events:
      - httpApi: "GET /chomper"
  chomperNext:
    handler: chomper-next.chomper
    events:
      - httpApi: "GET /chomper-next"
  chomper:
    handler: index.handler
    environment:
      TARGET_BUCKET: lfstats-scorecard-archive
      ROARR_LOG: true
      SOURCE_BUCKET: lfstats-incoming
    events:
      - s3:
          bucket: lfstats-incoming
          event: s3:ObjectCreated:*
          rules:
            - suffix: .tdf
          existing: true

custom:
  serverless-offline:
    httpPort: 4000
  bundle:
    ignorePackages:
      - pg-native
    linting: false
    externals:
      - slonik
