service: lfstats-chomper

frameworkVersion: "4"

useDotenv: true

package:
  individually: true

plugins:
  - serverless-offline

provider:
  name: aws
  stage: prod
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource:
            - "arn:aws:secretsmanager:us-east-1:474496752274:secret:prod/lfstats-MSO2km"
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::lfstats-incoming"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:DeleteObject"
          Resource:
            - "arn:aws:s3:::lfstats-incoming/*"
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::lfstats-scorecard-archive"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
          Resource:
            - "arn:aws:s3:::lfstats-scorecard-archive/*"
  runtime: nodejs20.x
  memorySize: 2048
  timeout: 600
  httpApi:
    cors: true

functions:
  chomperNext:
    handler: chomper-next.chomper
    events:
      - httpApi: "GET /chomper-next"
  chomperNextVersion:
    handler: chomper-next.version
    events:
      - httpApi: "GET /chomper-next-version"
  chomper:
    handler: index.handler
    environment:
      TARGET_BUCKET: lfstats-scorecard-archive
      ROARR_LOG: true
      SOURCE_BUCKET: lfstats-incoming
    events:
      - s3:
          bucket: lfstats-incoming
          event: s3:ObjectCreated:*
          rules:
            - suffix: .tdf
          existing: true
build:
  esbuild:
    external:
      - slonik
    exclude:
      - pg-native
custom:
  serverless-offline:
    httpPort: 4000
